name: tutor
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  video_player: ^2.9.2
  fluid_action_card: ^1.0.0+5
  carousel_slider: ^5.0.0
  supabase_flutter: ^2.8.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/flutter_intro.jpg
    - assets/images/python_advanced.png
    - assets/images/time_management.jpg
    - assets/images/public_speaking.png
    - assets/images/italian_cooking.jpg
    - assets/images/sushi_making.jpg
    - assets/icons/tuta.png
    - assets/icons/home.png
    - assets/icons/search.png
    - assets/icons/upload.png
    - assets/icons/profile.png

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700