name: tutor
description: "A Flutter application that provides users with a variety of lessons in different categories, including Educational, Personal Development, and Cuisine."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  video_player: ^2.9.2
  fluid_action_card: ^1.0.0+5
  carousel_slider: ^5.0.0
  supabase_flutter: ^2.8.0
  file_picker: ^8.1.2
  video_thumbnail: ^0.5.3
  path_provider: ^2.1.4
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter
  chewie: ^1.8.5
  share_plus: ^10.0.3
  dio: ^5.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  intl_utils: ^2.8.7

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/flutter_intro.jpg
    - assets/images/python_advanced.png
    - assets/images/time_management.jpg
    - assets/images/public_speaking.png
    - assets/images/italian_cooking.jpg
    - assets/images/sushi_making.jpg
    - assets/icons/tuta.png
    - assets/icons/home.png
    - assets/icons/download.png
    - assets/icons/love.png
    - assets/icons/search.png
    - assets/icons/upload.png
    - assets/icons/profile.png
    - assets/icons/share.png

flutter_intl:
  enabled: true
  arb_dir: lib/l10n
  output_dir: lib/generated
